### PR TITLE
Dockernization

### LINKED ISSUE #12: Dockerize Teddy-plus
Create the Docker version of Teddy-plus

### LINKED ISSUE #18: Unrecognized VM option 'UseParNewGC'
Error: Could not create the Java Virtual Machine. Error: A fatal exception has occurred. Program will exit.

ElasticSearch2.2.0 supports only Java 1.8

### LINKED ISSUE #22: build images of Elastic Search container
Elastic Search 2.2.0

### LINKED ISSUE #23: Build images of Teddy plus client system

### LINKED ISSUE #24: Net configuration between Elastic Search and client system

### LINKED ISSUE #25: write the scripts of docker-compose

### LINKED ISSUE #26: make output available on host machine
The outputs should be put under the host machine.

### LINKED ISSUE #27: make the master script
make the master script "Teddy.sh"

### LINKED ISSUE #28: clean up docker containers

### LINKED ISSUE #45: write how to use Teddy-plus using docker

### PR DESCRIPTION
**Pull request by gqlo**
- Both teddy client and elastic search images are tested and working on Linux.
- Docker-compose defines two services: teddy client and elastic search database
- network config using bridge 
- persistent volume
- To run against an git repo use command `./master {url}`

### CODE REVIEW

**Review by Phancisth — APPROVED** [review]
LGTM. Let's test the docker together in the next PBL class.

**Comment by ayanogami** [comment]
I try to this command, I had some errors

> ERROR: The Compose file './docker-compose.yml' is invalid because:
> Unsupported config option for networks: 'app_net'
> Unsupported config option for volumes: 'csv_data'
> Unsupported config option for services: 'elasticsearch'
> csv files and html plot are avaible at /var/docker/volumes/docker_csv_data
> 
> 

Let's check tomorrow

**Comment by ayanogami** [comment]
LGTM.
When I updated docker-compose version, then I can run your script.

**Review by ayanogami — APPROVED** [review]
LGTM

**Pull request merged**
